model_list:
  # deepai models (only working provider)
  - model_name: gpt-oss-120b
    litellm_params:
      model: openai/gpt-oss-120b
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: gemini-2.5-flash-lite
    litellm_params:
      model: openai/gemini-2.5-flash-lite
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: llama-4-scout
    litellm_params:
      model: openai/llama-4-scout
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: llama-3.3-70b-instruct
    litellm_params:
      model: openai/llama-3.3-70b-instruct
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: deepseek-v3.2
    litellm_params:
      model: openai/deepseek-v3.2
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: llama-3.1-8b-instant
    litellm_params:
      model: openai/llama-3.1-8b-instant
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: gemini-3-pro
    litellm_params:
      model: openai/gemini-3-pro
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: gpt-4.1-nano
    litellm_params:
      model: openai/gpt-4.1-nano
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: qwen3-30b
    litellm_params:
      model: openai/qwen3-30b
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: gpt-5-nano
    litellm_params:
      model: openai/gpt-5-nano
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: gemma-3-12b
    litellm_params:
      model: openai/gemma-3-12b
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: gemma2-9b
    litellm_params:
      model: openai/gemma2-9b
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: standard
    litellm_params:
      model: openai/standard
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY
  - model_name: super-genius
    litellm_params:
      model: openai/super-genius
      api_base: http://5.180.34.59:25529/v1
      api_key: os.environ/LITELLM_MASTER_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  drop_params: true
  set_verbose: false
  num_retries: 2
  request_timeout: 60
  disable_prisma_schema_update: true
