# Filtre pour détection d'abus sur endpoints sensibles
# image_gen et text_gen demandent beaucoup de ressources

[Definition]
failregex = ^.*Request: (POST|GET) (\/image\/generate|\/image\/edit|\/text\/generate) from <HOST>.*$
ignoreregex =
